# Generated by Django 3.2 on 2021-04-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
    ]
