# Generated by Django 3.2 on 2021-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
